# Generated by Django 4.2.5 on 2023-10-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_student_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
    ]
