# Generated by Django 4.2.5 on 2023-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_projectsinportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
